# App Name
spring.application.name=url-shortener

# MySQL Config for url
url.datasource.jdbc-url=jdbc:mysql://localhost:3306/urlShortner
url.datasource.username=root
url.datasource.password=123456789
url.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL Config for analytics
analytics.datasource.jdbc-url=jdbc:mysql://localhost:3306/urlAnalytics
analytics.datasource.username=root
analytics.datasource.password=123456789
analytics.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379